# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/michi/OneDrive/Documenten/Gitkraken directory/PROGH_Eindopdracht/Eindopdracht/Eindopdracht.srcs/sources_1/ip/clk_148/clk_148.xci
# IP: The module: 'clk_148' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/michi/OneDrive/Documenten/Gitkraken directory/PROGH_Eindopdracht/Eindopdracht/Eindopdracht.srcs/sources_1/ip/clk_148/clk_148_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_148'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/michi/OneDrive/Documenten/Gitkraken directory/PROGH_Eindopdracht/Eindopdracht/Eindopdracht.srcs/sources_1/ip/clk_148/clk_148.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_148'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/michi/OneDrive/Documenten/Gitkraken directory/PROGH_Eindopdracht/Eindopdracht/Eindopdracht.srcs/sources_1/ip/clk_148/clk_148_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_148'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/michi/OneDrive/Documenten/Gitkraken directory/PROGH_Eindopdracht/Eindopdracht/Eindopdracht.srcs/sources_1/ip/clk_148/clk_148.xci
# IP: The module: 'clk_148' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/michi/OneDrive/Documenten/Gitkraken directory/PROGH_Eindopdracht/Eindopdracht/Eindopdracht.srcs/sources_1/ip/clk_148/clk_148_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_148'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/michi/OneDrive/Documenten/Gitkraken directory/PROGH_Eindopdracht/Eindopdracht/Eindopdracht.srcs/sources_1/ip/clk_148/clk_148.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_148'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/michi/OneDrive/Documenten/Gitkraken directory/PROGH_Eindopdracht/Eindopdracht/Eindopdracht.srcs/sources_1/ip/clk_148/clk_148_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_148'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
